### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by afreitag33** [Gulf-IEA/scale-paper#2]
```[tasklist]
- [ ] figure out how to define acceptable steam time to fishing grounds (see issue)
- [ ] calculate Gini index (Kelly)
- [ ] calculate landscape metrics and edge:area (Seann)
- [ ] start Quarto document to put our final methods and results in (Suzana)
- [ ] geocode dealer addresses (Amy)
- [ ] link dealer addresses to Anthony's data (Amy/Suzana)
- [ ] decide what multivariate approach is best (see issue)
```
