### ISSUE TITLE
Workplan and due dates

### ISSUE THREAD

**Issue by afreitag33** [Gulf-IEA/scale-paper#5]
Rough deadlines for analysis and writing. All tasks are due COB the last day of the month (or whatever business day precedes it) to this Github repository. All final analysis and writing should go in the markdown document.
- [ ] Sep: finalize and format data sets, starting with how we are conceptualizing wetland loss and edge, visualize each one over the study period
- [ ] Oct: correlation matrices between wetland loss/edge and other nodes of the model; ID which have linear relationships and/or threshold effects
- [ ] Nov: multivariate correlations or linear models for each pathway in the conceptual model
- [ ] Dec/Jan: test different time periods (increments of 5 years) for relationships (exact stat method TBD)
- [ ] Feb: finalize conceptual model based on statistical results
- [ ] Mar task: test external factors (i.e. recreational fishing) and relationship to landings & revenue
- [ ] Apr: decide final story to tell/what stays in the journal article, where to submit
- [ ] May: write, write, write to get a share-able first draft
- [ ] June: share with broader GulfIEA team (or a few helpful volunteers) for review
- [ ] July: revisions + RPTS
- [ ] Aug: revisions from leadership's comments (if any)
- [ ] (logistical, drop-deadline) September 31st, 2024 (if not earlier): submit to journal
